### PR TITLE
[BAU] add Dockerfile

### PR DESCRIPTION
**Pull request by cyrusdobbs**
### Change description
Adds a Dockerfile 

- [NA] Unit tests and other appropriate tests added or updated
- [NA] README and other documentation has been updated / added (if needed)
- [X] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### CODE REVIEW

**Comment by cyrusdobbs** [comment]
> I'm receiving 'PermissionError: [Errno 13] Permission denied: '/app/app/static/.webassets-cache/8565f490c1ea1a134a129a699c0cb9cc' when I try to run.

@Joel-Pearce hmm I don't get that. Do you have the app running outside of docker as well by any chance?

**Review by nsnape — APPROVED** [review]
LGTM

**Comment by Joel-Pearce** [comment]
> > I'm receiving 'PermissionError: [Errno 13] Permission denied: '/app/app/static/.webassets-cache/8565f490c1ea1a134a129a699c0cb9cc' when I try to run.
> 
> @Joel-Pearce hmm I don't get that. Do you have the app running outside of docker as well by any chance?

No, I don't. Not sure why I'm getting it - everything looks fine to me. Must be a problem somewhere on my end.

**Comment by cyrusdobbs** [comment]
> > > I'm receiving 'PermissionError: [Errno 13] Permission denied: '/app/app/static/.webassets-cache/8565f490c1ea1a134a129a699c0cb9cc' when I try to run.
> > 
> > 
> > @Joel-Pearce hmm I don't get that. Do you have the app running outside of docker as well by any chance?
> 
> No, I don't. Not sure why I'm getting it - everything looks fine to me. Must be a problem somewhere on my end.

@Joel-Pearce I actually did just get that error.. seems to be intermittent. My guess is that it's something to do with multiple programs trying to access a the cache and a file-lock causing that error.. maybe and IDE and a container? I've removed the permissions change on the container and it did work after that but not sure if that was because of reboot or actual causation. One to watch I guess.

**Pull request merged**
